/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    posts: Post;
    events: Event;
    operations: Operation;
    crew: Crew;
    equipment: Equipment;
    faqs: Faq;
    'warning-presets': WarningPreset;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    operations: OperationsSelect<false> | OperationsSelect<true>;
    crew: CrewSelect<false> | CrewSelect<true>;
    equipment: EquipmentSelect<false> | EquipmentSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'warning-presets': WarningPresetsSelect<false> | WarningPresetsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'setup-state': SetupState;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'setup-state': SetupStateSelect<false> | SetupStateSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName: string;
  roles: ('super-admin' | 'organization-admin' | 'editor' | 'operations' | 'support')[];
  department?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  category: 'general' | 'news' | 'events' | 'operations' | 'team' | 'equipment';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  summary?: string | null;
  navigationLabel?: string | null;
  showInNavigation?: boolean | null;
  navigationOrder?: number | null;
  layout: (
    | {
        eyebrow?: string | null;
        headline: string;
        copy: string;
        primaryActionLabel: string;
        primaryActionHref: string;
        secondaryActionLabel?: string | null;
        secondaryActionHref?: string | null;
        heroImage?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        items?:
          | {
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'stats';
      }
    | {
        eyebrow?: string | null;
        headline: string;
        copy: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'rich-text';
      }
    | {
        eyebrow?: string | null;
        headline: string;
        links?:
          | {
              label: string;
              href: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'link-grid';
      }
    | {
        eyebrow?: string | null;
        headline: string;
        source: 'posts' | 'events' | 'operations' | 'crew' | 'equipment' | 'faqs';
        limit: number;
        intro?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'feed';
      }
    | {
        eyebrow?: string | null;
        headline: string;
        provider: 'dwd' | 'nina';
        presetKey?: string | null;
        ninaPresetKey?: string | null;
        intro?: string | null;
        regionLabel?: string | null;
        dwdRegionIds?:
          | {
              regionId: string;
              id?: string | null;
            }[]
          | null;
        dwdStates?:
          | {
              state: string;
              id?: string | null;
            }[]
          | null;
        forecastUrl?: string | null;
        warningMapUrl?: string | null;
        weatherMapUrl?: string | null;
        wildfireMapUrl?: string | null;
        showWeatherMap?: boolean | null;
        showWildfireMap?: boolean | null;
        ninaArs?: string | null;
        sourceUrl?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'warnings';
      }
    | {
        label?: string | null;
        title: string;
        text: string;
        primaryLabel: string;
        primaryHref: string;
        secondaryLabel?: string | null;
        secondaryHref?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'banner';
      }
    | {
        eyebrow?: string | null;
        headline: string;
        intro?: string | null;
        formMode: 'preset' | 'custom';
        presetKey?: ('contact' | 'join') | null;
        form?: (number | null) | Form;
        successMessage?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'form';
      }
    | {
        eyebrow?: string | null;
        headline: string;
        intro?: string | null;
        featuredEquipment?: (number | null) | Equipment;
        showStats?: boolean | null;
        showFeaturedProfile?: boolean | null;
        maxItems?: number | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'tech-overview';
      }
    | {
        eyebrow?: string | null;
        headline: string;
        intro?: string | null;
        equipment?: (number | null) | Equipment;
        showCompartments?: boolean | null;
        showHighlights?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'tech-details';
      }
    | {
        eyebrow?: string | null;
        headline: string;
        intro?: string | null;
        showStats?: boolean | null;
        showFilters?: boolean | null;
        maxItems?: number | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'operations-log';
      }
    | {
        eyebrow?: string | null;
        headline: string;
        intro?: string | null;
        videoId: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'youtube';
      }
    | {
        label: string;
        html: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'html';
      }
  )[];
  parent?: (number | null) | Page;
  breadcrumbs?:
    | {
        doc?: (number | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment".
 */
export interface Equipment {
  id: number;
  name: string;
  slug: string;
  callSign?: string | null;
  summary: string;
  heroImage?: (number | null) | Media;
  facts?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  compartments?:
    | {
        code: string;
        title: string;
        description?: string | null;
        image?: (number | null) | Media;
        showImagePlaceholder?: boolean | null;
        contents?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  category: 'oeffentlichkeitsarbeit' | 'einsatz' | 'ausbildung' | 'jugend';
  excerpt: string;
  content: string;
  featuredImage?: (number | null) | Media;
  showImagePlaceholder?: boolean | null;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  eventType: 'ausbildung' | 'uebung' | 'jugend' | 'organisation' | 'oeffentlich';
  visibility: 'public' | 'internal';
  startsAt: string;
  endsAt?: string | null;
  location: string;
  summary: string;
  featuredImage?: (number | null) | Media;
  showImagePlaceholder?: boolean | null;
  registrationEnabled?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operations".
 */
export interface Operation {
  id: number;
  operationNumber: string;
  alarmCode: string;
  category: 'brand' | 'hilfe' | 'wetter' | 'sonstiges';
  startedAt: string;
  location: string;
  summary: string;
  details?: string | null;
  featuredImage?: (number | null) | Media;
  showImagePlaceholder?: boolean | null;
  unitsInvolved?:
    | {
        unit: string;
        id?: string | null;
      }[]
    | null;
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crew".
 */
export interface Crew {
  id: number;
  name: string;
  role: string;
  qualification?: string | null;
  skills?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  focus?: string | null;
  portrait?: (number | null) | Media;
  showImagePlaceholder?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warning-presets".
 */
export interface WarningPreset {
  id: number;
  key: string;
  label: string;
  provider: 'dwd' | 'nina';
  regionLabel: string;
  isSystemPreset: boolean;
  dwdRegionIds?:
    | {
        regionId: string;
        id?: string | null;
      }[]
    | null;
  dwdStates?:
    | {
        state: string;
        id?: string | null;
      }[]
    | null;
  forecastUrl?: string | null;
  warningMapUrl?: string | null;
  weatherMapUrl?: string | null;
  wildfireMapUrl?: string | null;
  ninaArs?: string | null;
  sourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  requestFingerprint?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'operations';
        value: number | Operation;
      } | null)
    | ({
        relationTo: 'crew';
        value: number | Crew;
      } | null)
    | ({
        relationTo: 'equipment';
        value: number | Equipment;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'warning-presets';
        value: number | WarningPreset;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  roles?: T;
  department?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  navigationLabel?: T;
  showInNavigation?: T;
  navigationOrder?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              copy?: T;
              primaryActionLabel?: T;
              primaryActionHref?: T;
              secondaryActionLabel?: T;
              secondaryActionHref?: T;
              heroImage?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'rich-text'?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              copy?: T;
              id?: T;
              blockName?: T;
            };
        'link-grid'?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        feed?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              source?: T;
              limit?: T;
              intro?: T;
              id?: T;
              blockName?: T;
            };
        warnings?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              provider?: T;
              presetKey?: T;
              ninaPresetKey?: T;
              intro?: T;
              regionLabel?: T;
              dwdRegionIds?:
                | T
                | {
                    regionId?: T;
                    id?: T;
                  };
              dwdStates?:
                | T
                | {
                    state?: T;
                    id?: T;
                  };
              forecastUrl?: T;
              warningMapUrl?: T;
              weatherMapUrl?: T;
              wildfireMapUrl?: T;
              showWeatherMap?: T;
              showWildfireMap?: T;
              ninaArs?: T;
              sourceUrl?: T;
              id?: T;
              blockName?: T;
            };
        banner?:
          | T
          | {
              label?: T;
              title?: T;
              text?: T;
              primaryLabel?: T;
              primaryHref?: T;
              secondaryLabel?: T;
              secondaryHref?: T;
              id?: T;
              blockName?: T;
            };
        form?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              intro?: T;
              formMode?: T;
              presetKey?: T;
              form?: T;
              successMessage?: T;
              id?: T;
              blockName?: T;
            };
        'tech-overview'?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              intro?: T;
              featuredEquipment?: T;
              showStats?: T;
              showFeaturedProfile?: T;
              maxItems?: T;
              id?: T;
              blockName?: T;
            };
        'tech-details'?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              intro?: T;
              equipment?: T;
              showCompartments?: T;
              showHighlights?: T;
              id?: T;
              blockName?: T;
            };
        'operations-log'?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              intro?: T;
              showStats?: T;
              showFilters?: T;
              maxItems?: T;
              id?: T;
              blockName?: T;
            };
        youtube?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              intro?: T;
              videoId?: T;
              id?: T;
              blockName?: T;
            };
        html?:
          | T
          | {
              label?: T;
              html?: T;
              id?: T;
              blockName?: T;
            };
      };
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  showImagePlaceholder?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  eventType?: T;
  visibility?: T;
  startsAt?: T;
  endsAt?: T;
  location?: T;
  summary?: T;
  featuredImage?: T;
  showImagePlaceholder?: T;
  registrationEnabled?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operations_select".
 */
export interface OperationsSelect<T extends boolean = true> {
  operationNumber?: T;
  alarmCode?: T;
  category?: T;
  startedAt?: T;
  location?: T;
  summary?: T;
  details?: T;
  featuredImage?: T;
  showImagePlaceholder?: T;
  unitsInvolved?:
    | T
    | {
        unit?: T;
        id?: T;
      };
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crew_select".
 */
export interface CrewSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  qualification?: T;
  skills?:
    | T
    | {
        label?: T;
        id?: T;
      };
  focus?: T;
  portrait?: T;
  showImagePlaceholder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment_select".
 */
export interface EquipmentSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  callSign?: T;
  summary?: T;
  heroImage?: T;
  facts?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  compartments?:
    | T
    | {
        code?: T;
        title?: T;
        description?: T;
        image?: T;
        showImagePlaceholder?: T;
        contents?:
          | T
          | {
              label?: T;
              id?: T;
            };
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warning-presets_select".
 */
export interface WarningPresetsSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  provider?: T;
  regionLabel?: T;
  isSystemPreset?: T;
  dwdRegionIds?:
    | T
    | {
        regionId?: T;
        id?: T;
      };
  dwdStates?:
    | T
    | {
        state?: T;
        id?: T;
      };
  forecastUrl?: T;
  warningMapUrl?: T;
  weatherMapUrl?: T;
  wildfireMapUrl?: T;
  ninaArs?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  requestFingerprint?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  departmentName: string;
  taglinePrimary?: string | null;
  taglineSecondary?: string | null;
  announcement?: {
    enabled?: boolean | null;
    label?: string | null;
    message?: string | null;
  };
  theme?: {
    brandColor?: string | null;
    brandColorStrong?: string | null;
    surfaceColor?: string | null;
  };
  joinButton?: {
    label?: string | null;
    href?: string | null;
  };
  contact?: {
    email?: string | null;
    emergencyNumber?: string | null;
    address?: string | null;
  };
  legal?: {
    organizationName?: string | null;
    responsiblePerson?: string | null;
    imprintText?: string | null;
  };
  smtp?: {
    enabled?: boolean | null;
    host?: string | null;
    port?: number | null;
    secure?: boolean | null;
    username?: string | null;
    password?: string | null;
    fromName?: string | null;
    fromEmail?: string | null;
    ignoreTLS?: boolean | null;
    requireTLS?: boolean | null;
    skipVerify?: boolean | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "setup-state".
 */
export interface SetupState {
  id: number;
  status: 'not_started' | 'in_progress' | 'skipped' | 'completed';
  currentStep?: string | null;
  completedAt?: string | null;
  skippedAt?: string | null;
  completedBy?: (number | null) | User;
  version: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  departmentName?: T;
  taglinePrimary?: T;
  taglineSecondary?: T;
  announcement?:
    | T
    | {
        enabled?: T;
        label?: T;
        message?: T;
      };
  theme?:
    | T
    | {
        brandColor?: T;
        brandColorStrong?: T;
        surfaceColor?: T;
      };
  joinButton?:
    | T
    | {
        label?: T;
        href?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        emergencyNumber?: T;
        address?: T;
      };
  legal?:
    | T
    | {
        organizationName?: T;
        responsiblePerson?: T;
        imprintText?: T;
      };
  smtp?:
    | T
    | {
        enabled?: T;
        host?: T;
        port?: T;
        secure?: T;
        username?: T;
        password?: T;
        fromName?: T;
        fromEmail?: T;
        ignoreTLS?: T;
        requireTLS?: T;
        skipVerify?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "setup-state_select".
 */
export interface SetupStateSelect<T extends boolean = true> {
  status?: T;
  currentStep?: T;
  completedAt?: T;
  skippedAt?: T;
  completedBy?: T;
  version?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}